### ISSUE TITLE
Define runtime.yml

### ISSUE THREAD

**Issue by vexx32** [chocolatey/chocolatey-ansible#45]
Part of #20 

Per the [inclusion requirements](https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#requirements-for-collections-to-be-included-in-the-ansible-package) we must [define a `meta/runtime.yml` file in the collection directory](https://docs.ansible.com/ansible/latest/dev_guide/developing_collections.html#meta-directory), which describes at least the minimum Ansible version the collection is compatible with.

Given this module was an ansible core module initially, it probably makes sense to list the minimum Ansible version as whichever version introduced Galaxy -- 2.9? Need to check on that.

**Comment by jborean93** [comment]
Most collections have gone with `>=2.9.10` https://github.com/ansible-collections/community.general/blob/main/meta/runtime.yml#L2 because there was some features ( I know in a minor release :( ) that made deprecating collection details easier to do. You could probably get away with `>=2.9.0` though because the features added in .10 are mostly for the Python modules.
