### ISSUE TITLE
Add version constraints

### ISSUE THREAD

**Issue by mvorisek** [chocolatey/chocolatey-ansible#7]
Migrated from https://github.com/ansible-collections/community.windows/issues/39

This is a feature request. I propose to add version range constraint support to accept versions like [7.3, 7.4).

Chocolatey has no native support, hovewer the Chocolatey can lookup all versions like `choco list php --by-id-only -a` (or with `-e switch once https://github.com/chocolatey/choco/issues/1843 is solved). So I propose to allow to specify version by version range constraint, find the latest stable version and then proceed with instal of the discovered/fixed version.

**Comment by vexx32** [comment]
_Ideally_ this would be done in tandem with native Chocolatey support for this kind of thing. However, in the interim it's plausible a "good enough" solution can be added to this module to bridge the gap.

I'll mark this up for grabs for now in case other folks want to have a stab at it before one of us gets around to it, but I'll make a note to check back and see what an implementation would look like when I have some time available. 🙂

**Comment by vexx32** [comment]
Had an internal discussion with the team. We agree that this collection is probably the wrong place to put this logic. As I noted above, this should be supported from the `choco` side rather than the collection. If we build logic for this in the collection, we may run the risk of it breaking in future if the version resolution logic differs slightly in `choco` itself.

**Comment by mvorisek** [comment]
I understand, related with https://github.com/chocolatey/choco/issues/800 , 👍 there if interested in this feature and if you can, please help with the impl. Thanks!
